@startuml

left to right direction

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' 登場人物の定義
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

frame "Remote environment" {
  cloud "Cloud service" {
    [GitHub]
    [Travis CI]
  }
  [docker-compose 1]
  [docker-compose 2]
  [docker-compose 3]
  [docker-compose 4]
  [docker-compose 5]
  [docker-compose 6]
  [docker-compose 7]
  [docker-compose 8]
}

Actor Developer as dev
[docker-compose]

frame "Docker" {
  frame "Shellcheck container" {
    [shellcheck]
  }
  frame "Shfmt container" {
    [shfmt]
  }
  frame "Bash containers" {
    frame "Bash default container" {
      [bats 1]
      [bash default]
    }
    frame "Bash 3.0 container" {
      [bats 2]
      [bash 3.0]
    }
    frame "Bash 4.0 container" {
      [bats 3]
      [bash 4.0]
    }
    frame "Bash 4.1 container" {
      [bats 4]
      [bash 4.1]
    }
    frame "Bash 4.2 container" {
      [bats 5]
      [bash 4.2]
    }
    frame "Bash 4.3 container" {
      [bats 6]
      [bash 4.3]
    }
    frame "Bash 4.4 container" {
      [bats 7]
      [bash 4.4]
    }
    frame "Bash 5.0 container" {
      [bats 8]
      [bash 5.0]
    }
  }
}

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' フローの定義
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

' 開発者を起点とするフロー
dev -ri-> [docker-compose]

[docker-compose] -ri-> [shellcheck]
[shellcheck] -ri-> [Source code]

[docker-compose] -ri-> [shfmt]
[shfmt] -ri-> [Source code]

' Bats + Bashはセット
[docker-compose] -ri-> [bats 1]
[bats 1] -ri-> [bash default]
[bash default] -ri-> [Source code]

[docker-compose] -ri-> [bats 2]
[bats 2] -ri-> [bash 3.0]
[bash 3.0] -ri-> [Source code]

[docker-compose] -ri-> [bats 3]
[bats 3] -ri-> [bash 4.0]
[bash 4.0] -ri-> [Source code]

[docker-compose] -ri-> [bats 4]
[bats 4] -ri-> [bash 4.1]
[bash 4.1] -ri-> [Source code]

[docker-compose] -ri-> [bats 5]
[bats 5] -ri-> [bash 4.2]
[bash 4.2] -ri-> [Source code]

[docker-compose] -ri-> [bats 6]
[bats 6] -ri-> [bash 4.3]
[bash 4.3] -ri-> [Source code]

[docker-compose] -ri-> [bats 7]
[bats 7] -ri-> [bash 4.4]
[bash 4.4] -ri-> [Source code]

[docker-compose] -ri-> [bats 8]
[bats 8] -ri-> [bash 5.0]
[bash 5.0] -ri-> [Source code]

' GitHubにPushを起点とするフロー
dev -up-> [GitHub]
[GitHub] -up-> [Travis CI]
[Travis CI] -ri-> [docker-compose 1]
[Travis CI] -ri-> [docker-compose 2]
[Travis CI] -ri-> [docker-compose 3]
[Travis CI] -ri-> [docker-compose 4]
[Travis CI] -ri-> [docker-compose 5]
[Travis CI] -ri-> [docker-compose 6]
[Travis CI] -ri-> [docker-compose 7]
[Travis CI] -ri-> [docker-compose 8]
[docker-compose 1] -ri-> [bats 1]
[docker-compose 2] -ri-> [bats 2]
[docker-compose 3] -ri-> [bats 3]
[docker-compose 4] -ri-> [bats 4]
[docker-compose 5] -ri-> [bats 5]
[docker-compose 6] -ri-> [bats 6]
[docker-compose 7] -ri-> [bats 7]
[docker-compose 8] -ri-> [bats 8]

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' 位置調整
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

' Dockerコンテナグループでの配置
' shellcheck -down-> shfmt -down-> bash としたい
[shellcheck] -[hidden]- [shfmt]
[shfmt] -[hidden]- [bats 1]
[bats 1] -[hidden]- [bats 2]
[bash default] -[hidden]- [bash 3.0]
[bats 2] -[hidden]- [bats 3]
[bash 3.0] -[hidden]- [bash 4.0]
[bats 3] -[hidden]- [bats 4]
[bash 4.0] -[hidden]- [bash 4.1]
[bats 4] -[hidden]- [bats 5]
[bash 4.1] -[hidden]- [bash 4.2]
[bats 5] -[hidden]- [bats 6]
[bash 4.2] -[hidden]- [bash 4.3]
[bats 6] -[hidden]- [bats 7]
[bash 4.3] -[hidden]- [bash 4.4]
[bats 7] -[hidden]- [bats 8]
[bash 4.4] -[hidden]- [bash 5.0]

' GitHub, TravisCIなどのクラウド組はdevより上
dev -[hidden]up- [GitHub]
dev -[hidden]up- [Travis CI]
[docker-compose] -[hidden]up- [GitHub]
[docker-compose] -[hidden]up- [Travis CI]

[docker-compose 1] -[hidden]- [docker-compose 2]
[docker-compose 2] -[hidden]- [docker-compose 3]
[docker-compose 3] -[hidden]- [docker-compose 4]
[docker-compose 4] -[hidden]- [docker-compose 5]
[docker-compose 5] -[hidden]- [docker-compose 6]
[docker-compose 6] -[hidden]- [docker-compose 7]
[docker-compose 7] -[hidden]- [docker-compose 8]

@enduml
